# Generated by Django 3.2.9 on 2022-06-12 21:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSGOStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование игры')),
                ('player_id', models.CharField(max_length=255, verbose_name='Уникальное значение игрока')),
                ('elo', models.PositiveSmallIntegerField(blank=True, verbose_name='ELO')),
                ('kd_ratio', models.FloatField(blank=True, verbose_name='K/D Ratio')),
                ('average_kd_ratio', models.FloatField(blank=True, verbose_name='Average K/D Ratio')),
                ('average_hs', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Average Headshots %')),
                ('win_rate', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Win Rate %')),
            ],
            options={
                'verbose_name': 'Статистика CS:GO',
                'verbose_name_plural': 'Статистика CS:GO',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование факультета')),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультеты',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование группы')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.faculty', verbose_name='Факультет')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=150, verbose_name='Отчество')),
                ('nickname', models.CharField(max_length=150, verbose_name='Никнейм')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.group', verbose_name='Учебная группа')),
                ('stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.csgostats', verbose_name='Статистика игрока')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
    ]
