# Generated by Django 3.2.9 on 2022-06-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Наименование группы'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('name', 'faculty')},
        ),
    ]
