# Generated by Django 3.2.9 on 2022-06-12 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_remove_csgostats_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='stats',
        ),
    ]
