# Generated by Django 3.2.9 on 2022-06-13 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_remove_player_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csgostats',
            name='player_id',
        ),
        migrations.AddField(
            model_name='csgostats',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='csgo_stats', to='stats.player', verbose_name='Игрок'),
        ),
    ]
