# Generated by Django 3.2.9 on 2022-06-13 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_auto_20220613_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csgostats',
            name='player',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='csgo_stats', to='stats.player', verbose_name='Игрок'),
        ),
    ]
