# Generated by Django 3.2.9 on 2022-06-13 00:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_alter_csgostats_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csgostats',
            name='average_hs',
            field=models.PositiveSmallIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Average Headshots %'),
        ),
        migrations.AlterField(
            model_name='csgostats',
            name='win_rate',
            field=models.PositiveSmallIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Win Rate %'),
        ),
    ]
