# Generated by Django 3.2.9 on 2022-06-15 11:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_auto_20220613_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='DOTA2Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elo', models.PositiveSmallIntegerField(blank=True, verbose_name='ELO')),
                ('kd_ratio', models.FloatField(blank=True, verbose_name='K/D Ratio')),
                ('average_kd_ratio', models.FloatField(blank=True, verbose_name='Average K/D Ratio')),
                ('average_gm', models.FloatField(blank=True, verbose_name='Average Gold/minute')),
                ('win_rate', models.PositiveSmallIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Win Rate %')),
                ('player', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dota2_stats', to='stats.player', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Статистика DOTA 2',
                'verbose_name_plural': 'Статистика DOTA 2',
            },
        ),
    ]
