# Generated by Django 3.2.9 on 2022-06-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_dota2stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='faceit_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Faceit ID'),
        ),
    ]
